// Code generated by "stringer -type Signal signal.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Green-1]
	_ = x[Yellow-2]
	_ = x[Red-3]
}

const _Signal_name = "GreenYellowRed"

var _Signal_index = [...]uint8{0, 5, 11, 14}

func (i Signal) String() string {
	i -= 1
	if i < 0 || i >= Signal(len(_Signal_index)-1) {
		return "Signal(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Signal_name[_Signal_index[i]:_Signal_index[i+1]]
}
