// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

var TableNames = struct {
	Customer  string
	Migration string
	Todo      string
}{
	Customer:  "customer",
	Migration: "migration",
	Todo:      "todo",
}
