version: '3'

services:
  db:
    restart: always
    image: postgres:13-alpine
    container_name: tips-go-try-ormtest-db-postgres-container
    ports:
      - "22456:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=tips-go-try-ormtest-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local/data:/docker-entrypoint-initdb.d/

  testdb:
    restart: always
    image: postgres:13-alpine
    container_name: tips-go-try-ormtest-testdb-postgres-container
    ports:
      - "33456:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=tips-go-try-ormtest-testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local/testdata:/docker-entrypoint-initdb.d/
