// Code generated by "stringer -type=Subject subject.go"; DO NOT EDIT.

package subject

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Japanese-1]
	_ = x[Math-2]
	_ = x[English-3]
	_ = x[Science-4]
	_ = x[Social-5]
}

const _Subject_name = "JapaneseMathEnglishScienceSocial"

var _Subject_index = [...]uint8{0, 8, 12, 19, 26, 32}

func (i Subject) String() string {
	i -= 1
	if i < 0 || i >= Subject(len(_Subject_index)-1) {
		return "Subject(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Subject_name[_Subject_index[i]:_Subject_index[i+1]]
}
