// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_batch.sql

package infra

import (
	"context"
	"database/sql"
)

const createUsersBatch = `-- name: CreateUsersBatch :execresult
INSERT INTO users (name, created_at, updated_at) VALUES
   (?, NOW(), NOW()),
   (?, NOW(), NOW()),
   (?, NOW(), NOW()),
   (?, NOW(), NOW()),
   (?, NOW(), NOW())
`

type CreateUsersBatchParams struct {
	Name   string
	Name_2 string
	Name_3 string
	Name_4 string
	Name_5 string
}

func (q *Queries) CreateUsersBatch(ctx context.Context, arg CreateUsersBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUsersBatch,
		arg.Name,
		arg.Name_2,
		arg.Name_3,
		arg.Name_4,
		arg.Name_5,
	)
}
