// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package infra

import (
	"database/sql"
	"time"
)

type Class struct {
	ClassID   int64
	ClassName string
	GradeID   sql.NullInt64
}

type Comment struct {
	ID        int64
	Content   sql.NullString
	UserID    sql.NullInt64
	PostID    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Department struct {
	DepartmentID   int64
	DepartmentName string
}

type Employee struct {
	EmployeeID   int64
	FirstName    string
	LastName     string
	Salary       sql.NullString
	DepartmentID sql.NullInt64
	JoinDate     sql.NullTime
}

type Grade struct {
	GradeID   int64
	GradeName string
	SchoolID  sql.NullInt64
}

type Post struct {
	ID        int64
	Title     string
	Content   sql.NullString
	UserID    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type School struct {
	SchoolID   int64
	SchoolName string
}

type Student struct {
	StudentID int64
	Name      string
	ClassID   sql.NullInt64
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
