// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package infra

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	Content   sql.NullString
	UserID    sql.NullInt64
	PostID    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Post struct {
	ID        int64
	Title     string
	Content   sql.NullString
	UserID    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
