// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: posts.sql

package infra

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :execlastid
INSERT INTO posts (title, content, user_id) VALUES (?, ?, ?)
`

type CreatePostParams struct {
	Title   string
	Content sql.NullString
	UserID  sql.NullInt64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPost, arg.Title, arg.Content, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, content, user_id, created_at, updated_at
FROM posts
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT id, title, content, user_id, created_at, updated_at
FROM posts
WHERE user_id = ?
`

func (q *Queries) ListPostsByUser(ctx context.Context, userID sql.NullInt64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET title = ?, content = ?
WHERE id = ?
`

type UpdatePostParams struct {
	Title   string
	Content sql.NullString
	ID      int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost, arg.Title, arg.Content, arg.ID)
	return err
}
