// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: search.sql

package infra

import (
	"context"
)

const searchEmployees = `-- name: SearchEmployees :many
SELECT employee_id, first_name, last_name, salary, department_id, join_date FROM employees
`

func (q *Queries) SearchEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, searchEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.Salary,
			&i.DepartmentID,
			&i.JoinDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
