local:
  dialect: postgres
  datasource: host=localhost port=22456 dbname=tips-go-try-ormtest-db user=postgres password=yuckyjuice sslmode=disable
  dir: migration
  table: migration
localtest:
  dialect: postgres
  datasource: host=localhost port=33456 dbname=tips-go-try-ormtest-testdb user=postgres password=yuckyjuice sslmode=disable
  dir: migration
  table: migration
