// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Contents string
	Reviews  string
	Seller   string
}{
	Contents: "contents",
	Reviews:  "reviews",
	Seller:   "seller",
}
