output   = "repository"
pkgname  = "repository"

[psql]
  host   = "localhost"
  port   = 22456
  dbname = "tips-go-try-ormtest-db"
  user   = "postgres"
  pass   = "yuckyjuice"
  sslmode= "disable"
  blacklist = [
    "migration",
  ]
