INSERT INTO bugs (description) VALUES
                                   ('Application crashes when clicking on the save button.'),
                                   ('Database connection timeout occurs on heavy load.'),
                                   ('UI freezes when switching between tabs quickly.'),
                                   ('Memory leak detected in the image processing module.'),
                                   ('Login form does not validate empty email field.'),
                                   ('Session expiration happens too early after login.'),
                                   ('API returns 500 Internal Server Error for large requests.'),
                                   ('Slow response time when fetching dashboard statistics.'),
                                   ('Incorrect calculation of total amount in shopping cart.'),
                                   ('Push notifications are not delivered on iOS devices.'),
                                   ('Password reset email not being sent to the user.'),
                                   ('Race condition occurs when multiple users submit forms.'),
                                   ('Unable to upload image larger than 5MB on Chrome browser.'),
                                   ('SQL syntax error when inserting special characters.'),
                                   ('Payment gateway integration fails with invalid token.'),
                                   ('Cache is not cleared after user profile update.'),
                                   ('Cross-site scripting vulnerability found on comments page.'),
                                   ('Mobile app crashes on Android 12 when opening settings.'),
                                   ('Unexpected logout happens after idle for 10 minutes.'),
                                   ('Report generation takes more than 30 seconds to complete.'),
                                   ('Search functionality does not return expected results.'),
                                   ('WebSocket connection randomly disconnects after idle time.'),
                                   ('Multiple language translations are missing on signup page.'),
                                   ('Dark mode toggle does not persist after page refresh.'),
                                   ('Error 403 Forbidden when accessing restricted resources.'),
                                   ('Broken images appear on product detail page after deploy.'),
                                   ('Data duplication issue when importing CSV files.'),
                                   ('Autocomplete suggestions do not appear for long keywords.'),
                                   ('Scroll position resets unexpectedly after submitting form.'),
                                   ('Application fails to start when config.json is missing.');
