openapi: "3.0.3"

info:
  version: 1.0.0
  title: Todo API server
  description: Todo API

security: []

paths:
  /todos:
    post:
      summary: "TODO登録"
      description: "TODOを登録する。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoCreateInput"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
    get:
      summary: "全TODO返却"
      description: "全てのTODOを返却する。"
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        200:
          description: "全てのTODO"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
  /todos/{todoId}:
    get:
      summary: "指定TODO返却"
      description: "指定されたTODOを返却する。"
      parameters:
        - name: todoId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/TodoId"
      responses:
        200:
          description: "指定されたTODO"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"

components:
  schemas:
    CreatedAt:
      type: string
      format: date-time
      description: "作成日時"
      example: ""
    TodoId:
      type: integer
      format: int
      description: "TODOを一意に識別するキー"
      example: 1
      x-go-name: TodoID
    TodoTitle:
      type: string
      description: "TODOのタイトル"
      example: "床掃除"
    TodoContent:
      type: string
      description: "TODOの内容"
      example: "床掃除をする。"
    TodoCompleted:
      type: boolean
      description: "完了フラグ"
      example: true
    TodoCreateInput:
      type: object
      description: "作成するTODOの入力情報"
      properties:
        title:
          $ref: "#/components/schemas/TodoTitle"
        content:
          $ref: "#/components/schemas/TodoContent"
      required:
        - title
    Todo:
      allOf:
        - $ref: "#/components/schemas/TodoCreateInput"
        - type: object
          properties:
            id:
              $ref: "#/components/schemas/TodoId"
            completed:
              $ref: "#/components/schemas/TodoCompleted"
            createdAt:
              $ref: "#/components/schemas/CreatedAt"
          required:
            - id
            - createdAt